 services:

  db:
    image: mariadb:11
    container_name: ragnarok-db
    restart: unless-stopped

    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: ragnarok
      MARIADB_USER: ragnarok
      MARIADB_PASSWORD: ragnarok

    ports:
      - "3306:3306"

    volumes:
      - ./data/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin

    restart: unless-stopped

    environment:
      PMA_HOST: db

    depends_on:
      - db

    ports:
      - "8080:80"

  login:
    build: .
    container_name: login-server

    working_dir: /rathena

    command: ./login-server

    depends_on:
      - db

    ports:
      - "6900:6900"

  char:
    build: .
    container_name: char-server

    working_dir: /rathena

    command: ./char-server

    depends_on:
      - login

    ports:
      - "6121:6121"

  map:
    build: .
    container_name: map-server

    working_dir: /rathena

    command: ./map-server

    depends_on:
      - char

    ports:
      - "5121:5121"
